language: node_js
node_js: node
install: yarn install
before_script:
    - yarn run lint
script:
    - yarn run test
after_script:
    - yarn run coveralls
    - test $TRAVIS_BRANCH = "master" && yarn run doxdox
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: docs
  on:
    branch: master
